version : '3.7'
services:
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        
        environment:
            POSTGRES_PASSWORD: test123
            POSTGRES_USER: test123
            POSTGRES_DB: node-backenddb
            POSTGRES_HOST_AUTH_METHOD: trust
        

    app:
        
        image: node-webapp
        container_name: node-app-server
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - db
        ports: 
            - 5000:8080
        

